/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ztack;

import javax.swing.ImageIcon;

/**
 *
 * @author henry
 */
public class Ztack extends javax.swing.JFrame {
    ImageIcon AceOfClubs = new ImageIcon("src/ace_of_clubs.png");
    ImageIcon TwoOfClubs = new ImageIcon("src/2_of_clubs.png");
    ImageIcon ThreeOfClubs = new ImageIcon("src/3_of_clubs.png");
    ImageIcon FourOfClubs = new ImageIcon("src/4_of_clubs.png");
    ImageIcon FiveOfClubs = new ImageIcon("src/5_of_clubs.png");
    ImageIcon SixOfClubs = new ImageIcon("src/6_of_clubs.png");
    ImageIcon SevenOfClubs = new ImageIcon("src/7_of_clubs.png");
    ImageIcon EightOfClubs = new ImageIcon("src/8_of_clubs.png");
    ImageIcon NineOfClubs = new ImageIcon("src/9_of_clubs.png");
    ImageIcon TenOfClubs = new ImageIcon("src/10_of_clubs.png");
    ImageIcon JackOfClubs = new ImageIcon("src/jack_of_clubs2.png");
    ImageIcon QueenOfClubs = new ImageIcon("src/queen_of_clubs2.png");
    ImageIcon KingOfClubs = new ImageIcon("src/king_of_clubs2.png");
    ImageIcon AceOfHearts = new ImageIcon("src/ace_of_hearts.png");
    ImageIcon TwoOfHearts = new ImageIcon("src/2_of_hearts.png");
    ImageIcon ThreeOfHearts = new ImageIcon("src/3_of_hearts.png");
    ImageIcon FourOfHearts = new ImageIcon("src/4_of_hearts.png");
    ImageIcon FiveOfHearts = new ImageIcon("src/5_of_hearts.png");
    ImageIcon SixOfHearts = new ImageIcon("src/6_of_hearts.png");
    ImageIcon SevenOfHearts = new ImageIcon("src/7_of_hearts.png");
    ImageIcon EightOfHearts = new ImageIcon("src/8_of_hearts.png");
    ImageIcon NineOfHearts = new ImageIcon("src/9_of_hearts.png");
    ImageIcon TenOfHearts = new ImageIcon("src/10_of_hearts.png");
    ImageIcon JackOfHearts = new ImageIcon("src/jack_of_hearts2.png");
    ImageIcon QueenOfHearts = new ImageIcon("src/queen_of_hearts2.png");
    ImageIcon KingOfHearts = new ImageIcon("src/king_of_hearts2.png");
    ImageIcon AceOfSpades = new ImageIcon("src/ace_of_spades.png");
    ImageIcon TwoOfSpades = new ImageIcon("src/2_of_spades.png");
    ImageIcon ThreeOfSpades = new ImageIcon("src/3_of_spades.png");
    ImageIcon FourOfSpades = new ImageIcon("src/4_of_spades.png");
    ImageIcon FiveOfSpades = new ImageIcon("src/5_of_spades.png");
    ImageIcon SixOfSpades = new ImageIcon("src/6_of_spades.png");
    ImageIcon SevenOfSpades = new ImageIcon("src/7_of_spades.png");
    ImageIcon EightOfSpades = new ImageIcon("src/8_of_spades.png");
    ImageIcon NineOfSpades = new ImageIcon("src/9_of_spades.png");
    ImageIcon TenOfSpades = new ImageIcon("src/10_of_spades.png");
    ImageIcon JackOfSpades = new ImageIcon("src/jack_of_spades2.png");
    ImageIcon QueenOfSpades = new ImageIcon("src/queen_of_spades2.png");
    ImageIcon KingOfSpades = new ImageIcon("src/king_of_spades2.png");
    ImageIcon AceOfDiamonds = new ImageIcon("src/ace_of_diamonds.png");
    ImageIcon TwoOfDiamonds = new ImageIcon("src/2_of_diamonds.png");
    ImageIcon ThreeOfDiamonds = new ImageIcon("src/3_of_diamonds.png");
    ImageIcon FourOfDiamonds = new ImageIcon("src/4_of_diamonds.png");
    ImageIcon FiveOfDiamonds = new ImageIcon("src/5_of_diamonds.png");
    ImageIcon SixOfDiamonds = new ImageIcon("src/6_of_diamonds.png");
    ImageIcon SevenOfDiamonds = new ImageIcon("src/7_of_diamonds.png");
    ImageIcon EightOfDiamonds = new ImageIcon("src/8_of_diamonds.png");
    ImageIcon NineOfDiamonds = new ImageIcon("src/9_of_diamonds.png");
    ImageIcon TenOfDiamonds = new ImageIcon("src/10_of_diamonds.png");
    ImageIcon JackOfDiamonds = new ImageIcon("src/jack_of_diamonds2.png");
    ImageIcon QueenOfDiamonds = new ImageIcon("src/queen_of_diamonds2.png");
    ImageIcon KingOfDiamonds = new ImageIcon("src/king_of_diamonds2.png");
    ImageIcon CardBack = new ImageIcon("src/cardBack.png");
    /**
     * Creates new form Ztack
     */
    public Ztack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardOne1 = new javax.swing.JToggleButton();
        cardOne2 = new javax.swing.JToggleButton();
        cardOne3 = new javax.swing.JToggleButton();
        cardOne4 = new javax.swing.JToggleButton();
        cardOne5 = new javax.swing.JToggleButton();
        cardOne6 = new javax.swing.JToggleButton();
        cardTwo1 = new javax.swing.JButton();
        cardTwo2 = new javax.swing.JButton();
        cardTwo3 = new javax.swing.JButton();
        cardTwo4 = new javax.swing.JButton();
        cardTwo5 = new javax.swing.JButton();
        cardTwo6 = new javax.swing.JButton();
        deck = new javax.swing.JButton();
        pile = new javax.swing.JButton();
        points = new javax.swing.JLabel();
        endRoundButton = new javax.swing.JButton();
        NewGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTwo1ActionPerformed(evt);
            }
        });

        cardTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTwo2ActionPerformed(evt);
            }
        });

        cardTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTwo3ActionPerformed(evt);
            }
        });

        cardTwo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTwo4ActionPerformed(evt);
            }
        });

        cardTwo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTwo5ActionPerformed(evt);
            }
        });

        cardTwo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTwo6ActionPerformed(evt);
            }
        });

        deck.setText("Draw");

        pile.setText("Pile");

        points.setText("Points: 0");

        endRoundButton.setText("End Round");
        endRoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endRoundButtonActionPerformed(evt);
            }
        });

        NewGameButton.setText("New Game");
        NewGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardOne1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cardTwo1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardTwo2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardTwo3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardTwo4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardTwo5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardTwo6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cardOne2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cardOne6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardOne5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardOne4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pile, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(deck, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardOne3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(endRoundButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardTwo1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardTwo2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardTwo3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardTwo4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardTwo5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardTwo6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deck, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pile, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardOne3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardOne4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardOne5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardOne6, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardOne2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardOne1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(points)
                        .addGap(31, 31, 31)
                        .addComponent(endRoundButton)
                        .addGap(76, 76, 76)
                        .addComponent(NewGameButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTwo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTwo1ActionPerformed

    private void cardTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTwo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTwo2ActionPerformed

    private void cardTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTwo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTwo3ActionPerformed

    private void cardTwo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTwo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTwo4ActionPerformed

    private void cardTwo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTwo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTwo5ActionPerformed

    private void cardTwo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTwo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTwo6ActionPerformed

    private void endRoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endRoundButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endRoundButtonActionPerformed

    private void NewGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ztack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ztack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ztack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ztack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ztack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewGameButton;
    private javax.swing.JToggleButton cardOne1;
    private javax.swing.JToggleButton cardOne2;
    private javax.swing.JToggleButton cardOne3;
    private javax.swing.JToggleButton cardOne4;
    private javax.swing.JToggleButton cardOne5;
    private javax.swing.JToggleButton cardOne6;
    private javax.swing.JButton cardTwo1;
    private javax.swing.JButton cardTwo2;
    private javax.swing.JButton cardTwo3;
    private javax.swing.JButton cardTwo4;
    private javax.swing.JButton cardTwo5;
    private javax.swing.JButton cardTwo6;
    private javax.swing.JButton deck;
    private javax.swing.JButton endRoundButton;
    private javax.swing.JButton pile;
    private javax.swing.JLabel points;
    // End of variables declaration//GEN-END:variables
}
